const IMAGE_WIDTH = 64;
const IMAGE_HEIGHT = 64;
const IMAGE_LEGACY_HEIGHT = 32;

const IMAGE_THUMBNAIL_WIDTH = 180;
const IMAGE_THUMBNAIL_HEIGHT = 160;

export {IMAGE_WIDTH, IMAGE_HEIGHT, IMAGE_LEGACY_HEIGHT, IMAGE_THUMBNAIL_WIDTH, IMAGE_THUMBNAIL_HEIGHT};
